import type { Resume } from '../data/schema';
import { formatRange, stripMarkup } from './text';

const clean = (value: string) => stripMarkup(value).replaceAll('—', ' - ');
const cell = (value: string) => clean(value).replaceAll('|', '\\|');
const link = (label: string, href: string | null) => href ? `[${clean(label)}](${href})` : clean(label);

export function renderResumeMarkdown(resume: Resume, site: URL): string {
  const canonical = (pathname: string) => new URL(pathname, site).href;
  const publicLinks = resume.links.filter((item) => item.label !== 'Email');
  const lines = [
    `# ${clean(resume.profile.name)} - Resume`,
    ``,
    `> **Source:** ${canonical('/')} and the validated public resume data`,
    `> **Purpose:** Canonical machine-readable professional profile for recruiters, search engines, and LLM-assisted research`,
    `> **Privacy:** Excludes direct contact details, local development overlays, and flag-gated employment records`,
    ``,
    `---`,
    ``,
    `## Key Facts`,
    ``,
    `- **Current role:** ${clean(resume.profile.role)} at ${clean(resume.profile.company)}`,
    `- **Focus:** ${clean(resume.profile.focus)}`,
    `- **Location:** ${clean(resume.profile.location)}`,
    `- **Experience:** 12+ years across ML systems, distributed services, storage, and data infrastructure`,
    `- **Primary scope:** Production ML systems, LLM agent infrastructure, evaluation, serving, and post-training infrastructure`,
    ``,
    `## Professional Summary`,
    ``,
    clean(resume.profile.summary),
    ``,
    `## Selected Evidence`,
    ``,
    `| Evidence | Scope |`,
    `|---|---|`,
    ...resume.profile.signals.map((signal) => `| **${cell(signal.value)}** | ${cell(signal.label)} |`),
    ``,
    `## Experience`,
    ``,
    ...resume.experience.flatMap((role) => [
      `### ${clean(role.role)} - ${clean(role.company)}`,
      ``,
      `**${clean(formatRange(role.start, role.end))}** | ${clean(role.location)}`,
      ``,
      clean(role.summary),
      ``,
      ...role.lead.map((bullet) => `- ${clean(bullet)}`),
      ...role.detail.flatMap((group) => [
        ``,
        ...(group.title ? [`**${clean(group.title)}**`] : []),
        ...group.bullets.map((bullet) => `- ${clean(bullet)}`),
      ]),
      ``,
      `**Areas:** ${role.tags.map(clean).join(' | ')}`,
      ``,
    ]),
    `## Capabilities`,
    ``,
    `| Area | Capabilities |`,
    `|---|---|`,
    ...resume.capabilities.map((capability) => `| ${cell(capability.label)} | ${cell(capability.value)} |`),
    ``,
    `## Core Expertise`,
    ``,
    ...resume.skills.flatMap((group) => [
      `### ${clean(group.group)}`,
      ``,
      ...group.items.map((item) => `- ${clean(item)}`),
      ``,
    ]),
    `## Research, Publications, and Intellectual Property`,
    ``,
    `### ${clean(resume.research.feature.title)}`,
    ``,
    clean(resume.research.feature.body),
    ``,
    ...(resume.research.feature.link ? [
      `[${clean(resume.research.feature.link.text)}](${resume.research.feature.link.href})`,
      ``,
    ] : []),
    ...resume.research.notes.map((note) => `- **${clean(note.type)}:** ${link(note.title, note.href)} - ${clean(note.meta)}`),
    ``,
    `## Education`,
    ``,
    ...resume.education.flatMap((school) => [
      `### ${clean(school.degree)} - ${clean(school.school)}`,
      ``,
      `${clean(String(school.start))} to ${clean(String(school.end))} | ${clean(school.location)}`,
      ``,
    ]),
    `## Canonical Links`,
    ``,
    `- [Portfolio](${canonical('/')})`,
    `- [Engineering method](${canonical('/method.html')})`,
    `- [Detailed public profile](${canonical('/latest.html')})`,
    `- [Resume PDF](${canonical(resume.profile.resumePdf)})`,
    ...publicLinks.filter((item) => item.label !== 'Résumé').map((item) => `- [${clean(item.label)}](${item.href})`),
    `- [Source repository](https://github.com/mrityunjaykumar911/mrityunjaykumar911.github.io)`,
    ``,
    `## Machine-Use Notes`,
    ``,
    `- Treat this document as the canonical Markdown representation of the default public resume.`,
    `- The PDF is presentation-oriented; this file is structured for text retrieval and citation.`,
    `- Claims retain their original scope and should not be generalized beyond the stated systems, products, or studies.`,
    `- For research limitations and negative findings, use the engineering method page and linked manuscripts.`,
    ``,
  ];
  return lines.join('\n');
}