---------------------------- MODULE FlexWitness ----------------------------
(***************************************************************************)
(* MAXIMALITY CERTIFICATE for the Immobile condition in FlexFacets.        *)
(*                                                                         *)
(* A locally-evaluable condition sees only an item's own shape, so it must  *)
(* treat every context carrying that shape alike. Therefore one config in   *)
(* which an item of shape s is COUPLED proves that no sound local condition *)
(* may admit s. Below is one such config for EVERY shape Immobile rejects.  *)
(*                                                                         *)
(* If Maximal holds, Immobile is the weakest sound locally-evaluable        *)
(* condition on this domain: nothing weaker is sound, nothing stronger is   *)
(* necessary. Generated by sln/gen_witnesses.py; do not hand edit.          *)
(***************************************************************************)
EXTENDS Integers, FiniteSets

N   == 3
INF == 1000000
Bases   == {0, 60, 120}
Factors == {0, 1}
Mins    == {0, 60}
Maxes   == {1000000, 120}
Widths  == {120, 240, 360}

(* FlexFacets carries an exploration harness with VARIABLES cfg and item.   *)
(* This module uses only its SEMANTICS (Used, Immobile), which do not touch *)
(* those variables, so the instantiation substitutes an inert placeholder.  *)
Placeholder == << [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> INF], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> INF], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> INF] >>
F == INSTANCE FlexFacets WITH cfg <- Placeholder, item <- 1

(* Each witness: a config, the item under test, the width, and the sibling  *)
(* edit that moves it. Used(base)[item] # Used(perturbed)[item].            *)
Witnesses == {
  [ base |-> << [basis |-> 0, grow |-> 1, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 0, grow |-> 1, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 0, grow |-> 1, shrink |-> 0, min |-> 0, max |-> 120], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 0, grow |-> 1, shrink |-> 0, min |-> 0, max |-> 120], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 0, grow |-> 1, shrink |-> 0, min |-> 60, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 0, grow |-> 1, shrink |-> 0, min |-> 60, max |-> 1000000], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 0, grow |-> 1, shrink |-> 0, min |-> 60, max |-> 120], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 0, grow |-> 1, shrink |-> 0, min |-> 60, max |-> 120], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 0, grow |-> 1, shrink |-> 1, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 0, grow |-> 1, shrink |-> 1, min |-> 0, max |-> 1000000], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 0, grow |-> 1, shrink |-> 1, min |-> 0, max |-> 120], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 0, grow |-> 1, shrink |-> 1, min |-> 0, max |-> 120], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 0, grow |-> 1, shrink |-> 1, min |-> 60, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 0, grow |-> 1, shrink |-> 1, min |-> 60, max |-> 1000000], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 0, grow |-> 1, shrink |-> 1, min |-> 60, max |-> 120], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 0, grow |-> 1, shrink |-> 1, min |-> 60, max |-> 120], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 60, grow |-> 0, shrink |-> 1, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 60, grow |-> 0, shrink |-> 1, min |-> 0, max |-> 1000000], [basis |-> 120, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 60, grow |-> 0, shrink |-> 1, min |-> 0, max |-> 120], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 60, grow |-> 0, shrink |-> 1, min |-> 0, max |-> 120], [basis |-> 120, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 60, grow |-> 1, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 60, grow |-> 1, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 60, grow |-> 1, shrink |-> 0, min |-> 0, max |-> 120], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 60, grow |-> 1, shrink |-> 0, min |-> 0, max |-> 120], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 60, grow |-> 1, shrink |-> 0, min |-> 60, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 60, grow |-> 1, shrink |-> 0, min |-> 60, max |-> 1000000], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 60, grow |-> 1, shrink |-> 0, min |-> 60, max |-> 120], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 60, grow |-> 1, shrink |-> 0, min |-> 60, max |-> 120], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 60, grow |-> 1, shrink |-> 1, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 60, grow |-> 1, shrink |-> 1, min |-> 0, max |-> 1000000], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 60, grow |-> 1, shrink |-> 1, min |-> 0, max |-> 120], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 60, grow |-> 1, shrink |-> 1, min |-> 0, max |-> 120], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 60, grow |-> 1, shrink |-> 1, min |-> 60, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 60, grow |-> 1, shrink |-> 1, min |-> 60, max |-> 1000000], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 60, grow |-> 1, shrink |-> 1, min |-> 60, max |-> 120], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 60, grow |-> 1, shrink |-> 1, min |-> 60, max |-> 120], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 120, grow |-> 0, shrink |-> 1, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 120, grow |-> 0, shrink |-> 1, min |-> 0, max |-> 1000000], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 120, grow |-> 0, shrink |-> 1, min |-> 0, max |-> 120], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 120, grow |-> 0, shrink |-> 1, min |-> 0, max |-> 120], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 120, grow |-> 0, shrink |-> 1, min |-> 60, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 120, grow |-> 0, shrink |-> 1, min |-> 60, max |-> 1000000], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 120, grow |-> 0, shrink |-> 1, min |-> 60, max |-> 120], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 120, grow |-> 0, shrink |-> 1, min |-> 60, max |-> 120], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 120, grow |-> 1, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 120, grow |-> 1, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 240 ],
  [ base |-> << [basis |-> 120, grow |-> 1, shrink |-> 0, min |-> 60, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 120, grow |-> 1, shrink |-> 0, min |-> 60, max |-> 1000000], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 240 ],
  [ base |-> << [basis |-> 120, grow |-> 1, shrink |-> 1, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 120, grow |-> 1, shrink |-> 1, min |-> 0, max |-> 1000000], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 120, grow |-> 1, shrink |-> 1, min |-> 0, max |-> 120], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 120, grow |-> 1, shrink |-> 1, min |-> 0, max |-> 120], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 120, grow |-> 1, shrink |-> 1, min |-> 60, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 120, grow |-> 1, shrink |-> 1, min |-> 60, max |-> 1000000], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ],
  [ base |-> << [basis |-> 120, grow |-> 1, shrink |-> 1, min |-> 60, max |-> 120], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    pert |-> << [basis |-> 120, grow |-> 1, shrink |-> 1, min |-> 60, max |-> 120], [basis |-> 60, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000], [basis |-> 0, grow |-> 0, shrink |-> 0, min |-> 0, max |-> 1000000] >>,
    item |-> 1, width |-> 120 ]
}

(* Every rejected shape really is coupled somewhere. *)
Maximal ==
    \A w \in Witnesses :
        F!Used(w.base, w.width)[w.item] # F!Used(w.pert, w.width)[w.item]

(* And none of these witnessed shapes is admitted, i.e. we stay sound. *)
WitnessesRejected ==
    \A w \in Witnesses : ~F!Immobile(w.base, w.item)

VARIABLE tick
Init == tick = 0
Next == UNCHANGED tick
Spec == Init /\ [][Next]_tick
=============================================================================
